# gearbox:
#   version: 1

#   encoder:
#     pulses_per_motor_rotation: 903

#   ratios:
#     upper_motor_factor: 1.6666667 #25/15
#     lower_motor_factor: 1.0

#   motor_groups:
#     upper_motors: [0, 3]
#     lower_motors: [1, 2]

#   linear_conversion:
#     inner_shaft_lead_mm_per_rotation: 3.0
#     inner_shaft_translation_start_mm: 0.0
#     inner_shaft_translation_min_mm: -1.00
#     inner_shaft_translation_max_mm: 5.25

#   backlash: 
#     direction_deadband_pulses: 5
#     lower_motors_play_deg: 0
    
#     gear_l1_backlash_pulses: 50
#     gear_l1_backlash_deg: 12.0

#     gear_l2_backlash_pulses: 20
#     gear_l2_backlash_deg: 4.8

#     gear_r1_backlash_pulses: 60
#     gear_r1_backlash_deg: 24

#     gear_r2_backlash_pulses: 40
#     gear_r2_backlash_deg: 15.9

#   # Is not used now
#   offsets:
#     lower_motor_start_offset_deg: 20
#     gripper_start_offset_deg: 200
#   # Is not used now
#   hall_offsets:
#     hall1_offset_deg: 4
#     hall2_offset_deg: 10

#   gearbox_mapping:
#     gear_l1_motor: 3
#     gear_l2_motor: 0
#     gear_r1_motor: 1
#     gear_r2_motor: 2


gearbox:
  active_variant: gearbox_2
  variants: 
    gearbox_1:
      version: 1
      description: "old gearbox version, blue"

      encoder:
        pulses_per_motor_rotation: 903

      ratios:
        upper_motor_factor: 1.6666667 #25/15
        lower_motor_factor: 1.0

      motor_groups:
        upper_motors: [0, 3]
        lower_motors: [1, 2]

      linear_conversion:
        inner_shaft_lead_mm_per_rotation: 3.0
        inner_shaft_translation_start_mm: 0.0
        inner_shaft_translation_min_mm: -1.00
        inner_shaft_translation_max_mm: 5.25

      backlash: 
        direction_deadband_pulses: 5
        lower_motors_play_deg: 15

        gear_l1_backlash_positive_pulses: 50
        gear_l1_backlash_negative_pulses: 50
        # gear_l1_backlash_deg: 12.0

        gear_l2_backlash_positive_pulses: 20
        gear_l2_backlash_negative_pulses: 20
        # gear_l2_backlash_deg: 4.8

        gear_r1_backlash_positive_pulses: 60
        gear_r1_backlash_negative_pulses: 60
        # gear_r1_backlash_deg: 24

        gear_r2_backlash_positive_pulses: 40
        gear_r2_backlash_negative_pulses: 40
        # gear_r2_backlash_deg: 15.9

      gearbox_mapping:
        gear_l1_motor: 3
        gear_l2_motor: 0
        gear_r1_motor: 1
        gear_r2_motor: 2

      #Not used now
      offsets:
        lower_motor_start_offset_deg: 20
        gripper_start_offset_deg: 200

      hall_offsets:
        hall1_offset_deg: 4
        hall2_offset_deg: 10





    gearbox_2: #long collet
      version: 1
      description: "new version, with a longer collet and silver" 

      encoder:
        pulses_per_motor_rotation: 903

      ratios:
        upper_motor_factor: 1.6666667
        lower_motor_factor: 1.0

      motor_groups:
        upper_motors: [0, 3]
        lower_motors: [1, 2]

      linear_conversion:
        inner_shaft_lead_mm_per_rotation: 6.1
        inner_shaft_translation_start_mm: 0.0
        inner_shaft_translation_min_mm: -2.3
        inner_shaft_translation_max_mm: 7.1 
      
      backlash:
        direction_deadband_pulses: 5
        lower_motors_play_deg: 15 # dit is niet originele waarde toch? 

        gear_l1_backlash_positive_pulses: 50 #52
        gear_l1_backlash_negative_pulses: 50 #48

        gear_l2_backlash_positive_pulses: 25 #30
        gear_l2_backlash_negative_pulses: 25 #21

        gear_r1_backlash_positive_pulses: 53 #57
        gear_r1_backlash_negative_pulses: 53 #48

        gear_r2_backlash_positive_pulses: 49 #50
        gear_r2_backlash_negative_pulses: 49 #48

        # gear_r1_backlash_positive_pulses: 0
        # gear_r1_backlash_negative_pulses: 0

        # gear_r2_backlash_positive_pulses: 0
        # gear_r2_backlash_negative_pulses: 0

      #   # Gearbox 2 specific
      # collet_backlash_opening_mm: 0.0
      # collet_backlash_closing_mm: 0.0

      gearbox_mapping:
        gear_l1_motor: 3
        gear_l2_motor: 0
        gear_r1_motor: 1
        gear_r2_motor: 2

      offsets:
        lower_motor_start_offset_deg: 20
        gripper_start_offset_deg: 200

      hall_offsets:
        hall1_offset_deg: 4
        hall2_offset_deg: 10