instrument_state_node:
  ros__parameters:
    gearbox_output_topic: "/right/tool_control_node/gearbox_state"
    predicted_instrument_angles_topic: "/right/instrument_digital_twin/predicted_instrument_angles"

    hybrid_bend_enabled: true

    # Leave empty to automatically load the model selected during training.
    hybrid_bend_model_file: ""