tool_controller_node:
  ros__parameters:
    # topic: "/robot_cmd"
    topic: "/right/tool_control_node/instrument_angles"
    publish_rate: 100.0

    # mode can be: constant, triangle, sinusoid
    # value is ignored when mode is sinusoid/triangle
    # min, max, frequency are ingnored when mode is constant

    # dof: depends on control mode. roll/pitch/yaw/aperture or roll_shaft, benf, rool_tip, aperture

    dof1:
      mode: "constant"
      min: -1.57 #3.14
      max: 1.57 #3.14
      frequency: 0.1
      value: 0.0   


    dof2:
      mode: "constant"
      value: 0.0
      min: -0.25 #-0.25   
      max: 0.25 #0.25    
      frequency: 0.2
      sequence_modes: ["sinusoid", "triangle"]
      sequence_cycles: [5, 5]
      sequence_pause_duration: 5.0
      sequence_pause_led_start: 1.0
      sequence_pause_led_duration: 2.0  


    dof3:
      mode: "constant"
      min: -1.57 #3.14
      max: 1.57 #3.14
      frequency: 0.1
      value: 0.0
    

    dof4:
      mode: "sequence"
      value: 0.0
      min: 0.0
      max: 0.4

      frequency: 0.1
      # sequence_frequency_factors: [0.5, 1.0, 2.0]
      sequence_frequency_factors: [2.0, 1.0, 0.5]
      sequence_between_frequency_pause: 5.0
      sequence_range_factors: [0.5] #voor laatste test nieuw gb > grotere opening/ 
      sequence_between_range_pause: 5.0

      sequence_modes: ["sinusoid", "triangle"]
      sequence_cycles: [3, 3]
      sequence_pause_duration: 5.0
      sequence_pause_led_start: 1.0
      sequence_pause_led_duration: 2.0
