instrument:
  version: 1

  jaw_translation_min_mm: -1.25
  usable_jaw_translation_min_mm: 0.4 #gebasserd op video 

  jaw_translation_max_mm: 4.55
  usable_jaw_translation_max_mm: 3.61

  inner_shaft_translation_range_mm: 3.5 #defined based on measurements of inner axis. 

  articulation_factor: 16.0
  jaw_angle_deg_per_mm: 9 #8 #6.0
  between_jaws_deg_per_mm: 17.0 #18.0

  jaw_opening_threshold_mm: 0.05 #0.05
  jaw_closing_treshold_mm: 0.075

  jaw_opening_backlash_mm: 0.08 #0.08
  jaw_closing_backlash_mm: 0.05 #0.05

  bend_factor: 2.2 # 1.5
  instrument_bend_offset_deg: 0.0
  instrument_bend_backlash_positive_deg: 2.5
  instrument_bend_backlash_negative_deg: 9.0

  shaft_roll_sign: 1.0
  bend_sign: -1.0
  tip_rotation_sign: 1.0
  articulation_sign: 1.0

